- hosts: web
  become: yes
  tasks:
  - name: "update yum cache"
    yum:
      name: '*'
      state: latest

  - name: "install nginx"
    shell: "amazon-linux-extras install -y nginx1"

  - name: "create www directory"
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: delete default nginx site
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent

  - name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/conf.d/{{ domain }}.conf
      owner: root
      group: root
      mode: '0644'

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
  - name: Enable EPEL
    shell: "amazon-linux-extras install -y epel"

  - name: Install Certbot
    shell: "yum install -y certbot-nginx"

  - name: Obtain SSL/TLS certificate
    shell: certbot --nginx --non-interactive --agree-tos --email {{ email }} -d {{ domain }}
    environment:
      PATH: "{{ ansible_env.PATH }}:/usr/sbin"

 