- hosts: web
  tasks:
  - name: "sync static files"
    synchronize:
      src: ../dist/musicsource/
      dest: /var/www/{{ domain }}
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no